language: java
before_script:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda create -q -n test-environment r=3.6.2 
- source activate test-environment
- conda install -c bioconda/label/gcc7 r-xgr
- conda install -c bioconda nextflow

script: nextflow run XGR_PIPELINE.nf


