matrix:
  include:
    - language: r
      r:
      	- release

      script:
        - echo "r done and done"


    - language: java
      before_script:
        - curl -s https://get.nextflow.io | bash
      script:
        - ./nextflow run XGR_PIPELINE.nf


